FROM mamonu/moj-spark-jovyan:baseenv

RUN pip install pytest pytest-cov pytest-order poetry coveralls numpy==1.20 pyarrow==0.14.1 networkx==2.5.1 scipy==1.8 
RUN pip install "git+https://github.com/mamonu/graphframes.git@master#egg=graphframes&subdirectory=python"

ADD . /myfiles
WORKDIR /myfiles


ENTRYPOINT ["/myfiles/testrunner_entrypoint.sh"]
