name: docswithmkdoc

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: pip install --upgrade pip && pip install mkdocs==1.3.0 mknotebooks mkdocs-schema-reader mkdocs-material mkdocs-gen-files mkdocs-autorefs mkdocs-include-markdown-plugin  mkdocs-material-extensions mkdocs-mermaid2-plugin mkdocs-monorepo-plugin mkdocs-semiliterate mkdocs-simple-plugin mkdocstrings mkdocstrings-python mkdocstrings-python-legacy mkdocs-semiliterate
      - run: pip install jinja2==3.0.3 splink==3.0.0.dev18 && mkdocs gh-deploy --force
      - run: mkdocs --version
      - run: tree docs/
